### ISSUE TITLE
SFT - Définition générale du projet

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_suivi_flore_territoire#1]
A partir de Zones de Prospection (ZP) prospectées dans le protocole d'inventaire répété Bilan Stationnel (ex-Flore prioritaire), des ZP sont selectionnées pour faire office d'un suivi. Sur chacune de ces ZP, une espèce est prspectée par mailles de 100*100m et l'absence ou la présence de l'espèce est renseignée pour chaque maille.

La BDD s'appuie sur le module générique ``gn_monitoring`` permettant de gérer de manière centralisée les visites et les sites, de les étendre dans le schéma du protocole et d'y associer des observations.

Première version du MCD : 

![mcd-sft](https://user-images.githubusercontent.com/4418840/40996011-1006befe-6901-11e8-9216-092eae0e698c.jpg)

**Comment by camillemonchicourt** [comment]
Questions : 

- Le site de suivi est la ZP, pas les mailles de la ZP. Les mailles de la ZP correspondent aux observations faites lors de la visite d'un site (ZP dans notre cas qui sont des polygones). 
- Du coup, pas sur du lien entre ``t_base_sites`` et ``li_grids``. Si il y en a un, cela passe par ``l_areas``, ``li_grids`` en étant une extension.
- Pour savoir quels sites sont concernés par le protocole, on utile ``cor_site_application`` ? On en a surement déjà parlé mais le lien n'est-il pas plutôt à faire avec ``gn_commons.t_modules`` ? utilisateurs.t_applications étant plutôt dédié à la gestion des droits (https://github.com/PnX-SI/GeoNature/issues/358).

**Comment by TheoLechemia** [comment]
Ok pour la 1ere remarque. Les site de suivi sont bien les ZP. Donc il faut faire le lien avec ``l_area``. 
Pour savoir quels sites sont suivi dans l'appli, c'est bien la table ``cor_site_app``. Le ``id_app`` étant une clé étrangère de la table ``gn_commons.t_modules``

**Comment by camillemonchicourt** [comment]
Un site pouvait être utilisé par plusieurs applications, pour savoir qu'elles visites remontées dans le module, il faut aussi ajouter un lien entre Visites et Modules.

Sinon pour le fonctionnement général, je propose de se baser sur ce qui a été défini dans le protocole similaire Suivi Habitat Territoire (https://github.com/PnX-SI/gn_module_suivi_habitat_territoire/issues/1) : 

- L'administrateur/référent définit en amont les ZP suivies, leurs mailles et le taxon suivi par ZP (à voir si à terme on gère ça en partie dans l'interface)
- L'agent qui accède au module arrive sur une carte/liste des ZP suivies (éventuellement filtrées par ses droits CRUVED). Dans la liste des ZP, il voit le nombre de visites existantes sur chaque ZP, la date de la dernière visite, l'espèce suivie dans chaque ZP. Il peut filtrer par taxon, observateur, année de visites. Il peut aussi exporter les ZP et les visites en fonction de son CRUVED.
- Il peut afficher le détail d'une ZP. Il accède alors aux infos sur le site (ZP), il peut consulter le détail de chaque visite. En bonus, on pourra lui afficher des premières analyses carto ou statistiques sur l'évolution  des absences/présences sur les mailles
- Il peut aussi ajouter une visite sur un site (ZP). Il renseigne la date, les observateurs et les usages de la visite. Puis il clique sur la carte pour définir l'absence ou la présence de l'espèce.
- Selon son CRUVED il peut modifier les visites.

**Comment by camillemonchicourt** [comment]
On a des premières données sur la potentielle du Dauphiné avec des traitements réalisés sur la BDD Flore prioritaire pour avoir un état 0. 

![test](https://user-images.githubusercontent.com/4418840/41093523-da92b5d8-6a4b-11e8-8bc5-ae58f5dfed24.jpg)

**Comment by camillemonchicourt** [comment]
C'est un peu long, mais le schéma de la BDD devrait s'appeler ``pr_monitoring_flora_territory``.

**Comment by Khanh-Chau** [comment]
Nouvelle version du MCD_Suvi_Territoire

![mcd_modif_100618](https://user-images.githubusercontent.com/39497487/41220520-f810cf00-6d61-11e8-94ec-f7fee8001c69.jpg)

**Comment by Khanh-Chau** [comment]
Dernière modification du MCD Suivi Territoire
![mcd_modif_100618](https://user-images.githubusercontent.com/39497487/41292846-fb2df490-6e53-11e8-813e-13da3f254528.jpg)

**Comment by Khanh-Chau** [comment]
Document explicatif du MCD
[MCD_debriefing_110618.pdf](https://github.com/PnX-SI/gn_module_suivi_flore_territoire/files/2094166/MCD_debriefing_110618.pdf)

**Comment by camillemonchicourt** [comment]
Concernant la présentation et l'avancement du travail, le rapport de mi-stage de @Khanh-Chau est disponible en ligne : http://geonature.fr/documents/2018-06-Nguyen-Khanh-Chau-Rapport-mi-stage.pdf

**Comment by Amaadou** [comment]
Bonjour, C'est Nabil Designer chez Natural Solutions, je joint ici les maquettes mises à jours du module habitat

![ecran-1](https://user-images.githubusercontent.com/44839870/48134611-bb4c9780-e29a-11e8-9bdc-d1af86e50aaf.png)
![ecran-consultation](https://user-images.githubusercontent.com/44839870/48134612-bb4c9780-e29a-11e8-8089-8a8ff8676298.png)
![ecran-saisie](https://user-images.githubusercontent.com/44839870/48134614-bbe52e00-e29a-11e8-8605-4afde3835f0b.png)

**Comment by camillemonchicourt** [comment]
OK je viens de basculer ces maquettes dans le bon projet car ici il s'agit d'un module d'un protocole de Suivi Flore.

https://github.com/PnX-SI/gn_module_suivi_habitat_territoire/issues/1

Les retours seront fait sur cet autre issue.

**Comment by camillemonchicourt** [comment]
Rapport final de stage de Khanh-Chau : http://geonature.fr/documents/2018-09-Nguyen-Khanh-Chau-Rapport-stage-M2DCISS.pdf
Et soutenance : http://geonature.fr/documents/2018-09-Nguyen-Khanh-Chau-Soutenance-stage-M2DCISS.pdf
