### ISSUE TITLE
Intégration des données historiques et ZP

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_suivi_flore_territoire#22]
- Vérifier et documenter la méthode d'intégration de ZP dans la BDD
- Mettre en place et documenter une procédure d'intégration de données historiques (visites de mailles sur des ZP)

**Comment by camillemonchicourt** [comment]
Une documentation a été réalisée : https://github.com/PnX-SI/gn_module_suivi_flore_territoire/blob/master/docs/import-data.rst

Des scripts ont été commencé.

**Comment by jpm-cbna** [comment]
Des scripts pour intégrer les taxons, nomenclatures, mailles, sites et visites ont été développés.

Ils sont paramétrables via le fichier _settings.ini_ et possèdent tous des options permettant entre autre de lancer la suppression de l'import précédemment réalisé. Voir la [documentation sur l'import des données](docs/import-data.md).

Chacun d'entre eux s'assure de ne pas créer de doublons.
