### ISSUE TITLE
Exporter les mailles d'un site (ZP)

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_suivi_flore_territoire#24]
Pouvoir exporter les mailles d'une ZP dans un format utilisables par les appareils mobiles, dans Oruxmaps par exemple. 

En GeoJSON ou SHP à minima car c'est disponible dans GeoNature comme format. Éventuellement GPX, KML ?

**Comment by gildeluermoz** [comment]
Pour oruxmaps, le KML c'est parfait, les autres formats je ne suis pas sûr qu'il lise.

**Comment by camillemonchicourt** [comment]
Ouais ça serait une bonne révolution si il lisait le GeoJSON, car le KML c'est assez pourri. 
Mais j'ai pas l'impression que ce soit encore possible.

Bon mais déjà le jour où on arrivera à quitter le Shapefiles, ça sera une bonne chose : http://switchfromshapefile.org/ :-)

**Comment by jpm-cbna** [comment]
L'export des mailles de toutes les visites d'un site est maintenant disponible en geojson, csv et shape.
