### ISSUE TITLE
Installer - Sites non affichées

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_suivi_flore_territoire#26]
L'installation du module a été pas mal testée et ajustée aujourd'hui, dernier jour de @Khanh-Chau 

Cependant le module ne renvoie aucun site. 

Potentiellement car il n'y a pas de communes sur nos GeoNature à l'endroit où on été insérées les ZP d'exemple. 

En effet la route ``/sites`` filtre sur communes : https://github.com/PnX-SI/gn_module_suivi_flore_territoire/blob/master/backend/blueprint.py#L31-L61

Si on refait la requête en SQL, celle-ci ne retourne aucune ligne : 

```
SELECT ti.id_infos_site, ti.cd_nom,
            max(tv.visit_date_min),
            tx.nom_complet,
            count(tv.id_base_visit),
            bo.nom_organisme,
            la.area_name
FROM pr_monitoring_flora_territory.t_infos_site ti
LEFT JOIN gn_monitoring.t_base_visits tv ON tv.id_base_site = ti.id_base_site
LEFT JOIN taxonomie.taxref tx ON ti.cd_nom = tx.cd_nom
LEFT JOIN gn_monitoring.cor_visit_observer cvo ON cvo.id_base_visit = tv.id_base_visit
LEFT JOIN utilisateurs.t_roles tr ON tr.id_role = cvo.id_role
LEFT JOIN utilisateurs.bib_organismes bo ON bo.id_organisme = tr.id_organisme
LEFT JOIN gn_monitoring.cor_site_area csa ON csa.id_base_site = ti.id_base_site
LEFT JOIN ref_geo.l_areas la ON la.id_area = csa.id_area
WHERE la.id_type = 25
GROUP BY ti.id_infos_site, ti.cd_nom, tx.nom_complet, bo.nom_organisme, la.area_name
```

La requête est à ajuster pour retourner les sites, même si ils n'ont pas de commune dans ``gn_monitoring.cor_site_area``

**Comment by gildeluermoz** [comment]
Bizarre car comme tu ne fais que des left joint, si tu as qq chose dans pr_monitoring_flora_territory.t_infos_site, ça devrait remonter. Essaies de retirer le where pour voir si ça vient des communes.
Autre remarque un count(monchamp) c'est pareil qu'un count(*). Voir si besoin d'un count(DISTINCT monchamp).

**Comment by TheoLechemia** [comment]
Fait: https://github.com/PnX-SI/gn_module_suivi_flore_territoire/commit/41b11b94d44436ca97bcac7cb607fefe816a5423
