### ISSUE TITLE
Install_db - Remplir cor_sites_applications

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_suivi_flore_territoire#28]
Dans les scripts SQL, on remplit la table ``gn_monitoring.cor_site_application``, utile au fonctionnement de l'application : https://github.com/PnX-SI/gn_module_suivi_flore_territoire/blob/master/data/SFT_data.sql#L61-L65

Pour cela on utilise la variable ``MY_ID_MODULE``. Cependant quand on installe le module, on ne connait pas encore son ``id_module`` donc il faudrait faire sans cela et supprimer ce paramètre du ``setting.ini``.

On a essayé de la modifier en : 

```
-- Insérer dans cor_site_application les sites suivis de ce module
INSERT INTO gn_monitoring.cor_site_application 
with idapp AS(
SELECT id_application FROM utilisateurs.t_applications
WHERE nom_application = 'suivi_flore_territoire';
)
SELECT bs.id_base_site, idapp
FROM gn_monitoring.t_base_sites bs
JOIN pr_monitoring_flora_territory.zp_tmp zp ON bs.base_site_code  = zp.id::character varying;
```

Mais cela n'a pas fonctionné. 
De plus il ne faudrait pas utiliser ``pr_monitoring_flora_territory.zp_tmp`` dans cette requête.

A creuser.

**Comment by gildeluermoz** [comment]
Je creuserai mais déjà il faudrait mettre tes champs dans la partie insert et dans le select après le with, il faut un idap.id_application et pas seulement idap.

**Comment by camillemonchicourt** [comment]
OK c'est réglé : https://github.com/PnX-SI/gn_module_suivi_flore_territoire/commit/929869b6007bdf953042f7597d71b69104e457f4

Par contre on utilise le nom de l'application en dur désormais, un peu fragile.
