### ISSUE TITLE
Liste des taxons suivis

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_suivi_flore_territoire#30]
Le module s'appuie sur une liste de taxons définies au niveau de TaxHub. 

J'ai créé une liste de base : https://github.com/PnX-SI/gn_module_suivi_flore_territoire/commit/a3a01c7965ed23f66856b4b028c41c4f8ad56fee

On a déjà une liste SAISIE OCCTAX (id = 100) donc j'ai mis ID = 30 au pif pour celle-là, mais ça n'a pas vraiment de sens. 

Je me pose la question de basculer le champs ``id_liste`` de ``taxonomie.bib_listes`` en serial et de ne pas commencer avec ces id_listes 100 et 30 (et ensuite ???) qui ont peu de sens.

**Comment by gildeluermoz** [comment]
c'est toujours pareil. Soit on gère les id_listes à la main, soit on laisse la base les gérer et on s'organise pour récupérer les id générés. C'est plus propres car cela évite d'installer le module dans une base ou la liste 30 existerait déjà... mais aussi plus complexe à gérer.
TODO

**Comment by camillemonchicourt** [comment]
Oui c'est ça. OK on reste comme ça pour le moment.
