### ISSUE TITLE
Alerte visite existante cette année

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_suivi_flore_territoire#31]
L'alerte semble fonctionner quand on tente de saisir une visite sur une ZP qui a déjà été visitée cette année. 
Par contre, après cela, même si on modifie l'année de la visite en cours de saisie, l'enregistrement ne fonctionne pas.

**Comment by jpm-cbna** [comment]
Ce ticket semble correspondre au même problème que ticket #37
