### ISSUE TITLE
Nettoyer les filtres

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_suivi_flore_territoire#34]
Pour les filtres Organismes et Communes, il y a encore des valeurs listées en dur (Test1, Test2) à supprimer.

A voir aussi si la valeur TOUS dans les listes est utile.

Enfin le filtre Organisme, affiche chaque organisme autant de fois qu'il y a d'utilisateur dans celui-ci.

**Comment by camillemonchicourt** [comment]
Les valeurs de test ont été supprimées : https://github.com/PnX-SI/gn_module_suivi_flore_territoire/commit/35adf149fa65fdb0d792ece61a9a04886769a55e

**Comment by jpm-cbna** [comment]
- [x] Supprimer les valeurs en dur (déjà réalisé)
- [x] Faire le point sur l'utilité de la valeur "Tous" dans les filtres
- [x] Corriger la duplication des organismes

**Comment by jpm-cbna** [comment]
Concernant l'utilité de l'entrée "Tous", cela me semble nécessaire pour désactiver un filtre précédemment sélectionné. Sinon qu'elle était l'alternative envisagée ?

**Comment by jpm-cbna** [comment]
Je viens de constater qu'effectivement l'entrée "Tous" des filtres fait doublon avec l'entrée "-- Sélectionner un filtre --". Ces  2 entrées réinitialise le filtre. Il serait effectivement judicieux de garder seulement l'une d'entre elle.

**Comment by camillemonchicourt** [comment]
Oui on a l'habitude de laisser vide "-- Selectionner..--" plutot que TOUS.

**Comment by jpm-cbna** [comment]
Si je comprends bien, je laisse les entrées "-- Sélectionner une commune --", "-- Sélectionner un organisme -- " pour réinitialiser chacun de ces filtres et je supprime les entrées "Tous" ?

**Comment by camillemonchicourt** [comment]
Je me suis embrouillé.
A voir comment c'est par ailleurs dans GeoNature.
De ce que je vois, on a plutôt une entrée TOUS dans les listes déroulantes des filtres, dans Occtax, Synthèse ...
