### ISSUE TITLE
Liste des observateurs

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_suivi_flore_territoire#35]
Par défaut la liste des observateurs, se base la liste "Observateurs Occtax" (``utilisateurs.t_menus.id_menu`` = 1) créée lors de l'installation d'Occtax. 

L'``id_menu`` utilisé est paramétrable (https://github.com/PnX-SI/gn_module_suivi_flore_territoire/blob/master/config/conf_gn_module.toml.example#L14)
Il lui faudrait donc plutôt une liste dédiée ("Observateur SFT"). 

A voir si on la créé lors de la création de la BDD de SFT et comment on la peuple par défaut (avec les groupes "Grp_admin" et "Grp_en_poste" par exemple, si ils existent encore dans la table ``utilisateurs.t_toles``)

**Comment by jpm-cbna** [comment]
Le paramètre "`observers_list_id`" a été ajouté dans _settings.ini_ afin de pouvoir définir un id de liste d'observateur spécifique au module Sft.
