### ISSUE TITLE
Impossible de modifier une visite

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_suivi_flore_territoire#37]
Le controle d'année pense qu'on essaie de créer une visite sur une année où il y en a déjà une. Et il bloque l'enregistrement.

**Comment by jpm-cbna** [comment]
Le blocage de l'enregistrement n'a lieu qu'une fois le message d'erreur du contrôle d'année affiché et après correction de la visite comme indiqué dans le ticket #31. Le toaster affiche alors "Une erreur est survenue !". Je n'ai pas pu reproduire le problème indiqué ici  dans une autre situation.
