### ISSUE TITLE
Liste des communes d'une ZP

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_suivi_flore_territoire#38]
La commune est affichée autant de fois qu'il y a d'observateurs dans les différentes visites

**Comment by camillemonchicourt** [comment]
Sûrement le même problème que celui corrigé ici : https://github.com/PnX-SI/gn_module_suivi_habitat_territoire/commit/dc567ba30469f6b2d4a313ea261ec82b0ac93eed

**Comment by camillemonchicourt** [comment]
Et autant de fois que de visites sur le site

**Comment by jpm-cbna** [comment]
Déjà résolue avec le ticket #52 .
