### ISSUE TITLE
Ajout d'une visite bloqué par absence de jeux de données

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/gn_module_suivi_flore_territoire#51]
Lorsque nous tentons d'ajouter une visite après avoir rempli le formulaire un message "Une erreur est survenue" apparait. Elle est du à ceci:
```
(psycopg2.errors.NotNullViolation) ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « id_dataset »
DETAIL:  La ligne en échec contient (9, 115, null, null, null, 2020-03-01, 2020-03-01, null, null, Test, c28ff9f7-227b-41a1-a6c4-bdbcd3417aa9, 2020-03-24 19:04:35.744845, null)

[SQL: INSERT INTO gn_monitoring.t_base_visits (id_base_site, id_digitiser, id_dataset, id_module, visit_date_min, visit_date_max, id_nomenclature_obs_technique, id_nomenclature_grp_typ, comments, uuid_base_visit, meta_create_date, meta_update_date) VALUES (%(id_base_site)s, %(id_digitiser)s, %(id_dataset)s, %(id_module)s, %(visit_date_min)s, %(visit_date_max)s, %(id_nomenclature_obs_technique)s, %(id_nomenclature_grp_typ)s, %(comments)s, (SELECT uuid_generate_v4() AS uuid_generate_v4_1), %(meta_create_date)s, %(meta_update_date)s) RETURNING gn_monitoring.t_base_visits.id_base_visit]
[parameters: {'id_base_site': '115', 'id_digitiser': None, 'id_dataset': None, 'id_module': None, 'visit_date_min': '2020-03-01', 'visit_date_max': '2020-03-01', 'id_nomenclature_obs_technique': None, 'id_nomenclature_grp_typ': None, 'comments': 'Test', 'meta_create_date': None, 'meta_update_date': None}]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

Est ce que l'obligation d'avoir un `id_dataset` est due à une évolution de GeoNature ?

**Comment by camillemonchicourt** [comment]
Oui c'est normal et indiqué ici : https://github.com/PnX-SI/GeoNature/issues/812
C'est aussi détaillé dans les notes de la version 2.3.0 dans laquelle cela a été intégré : https://github.com/PnX-SI/GeoNature/releases/tag/2.3.0

On était parti sur le principe qu'un module de suivi était égal à un seul dataset. Donc dans un module comme SFT, l'``id_dataset`` de toutes les données produites dans le module pourraient être défini dans les paramètres du module. 

Cet ``id_dataset`` est essentiel pour pouvoir pousser les données du module automatiquement dans la Synthèse, voir https://github.com/PnX-SI/gn_module_suivi_flore_territoire/issues/23
