### ISSUE TITLE
Fiche site - Nom commune dupliqué

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/gn_module_suivi_flore_territoire#52]
Sur la fiche d'un site, le nom de la  même commune s'affiche autant de fois que le site contient de visites.
Il ne devrait pas y avoir de doublon de noms de commune.

**Comment by camillemonchicourt** [comment]
Voir aussi https://github.com/PnX-SI/gn_module_suivi_flore_territoire/issues/38
