### ISSUE TITLE
Ne pas utiliser le terme ZP dans le code

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/gn_module_suivi_flore_territoire#55]
Le terme ZP (Zone de prospection) n'est pas générique. Il faudrait remplacer le terme "ZP" présent dans le code par "Site". Ce terme doit être paramétrable quand il doit être affiché sur l'interface.

Ex. : le module "zp-map-list" pourra ainsi devenir "list-site".

**Comment by camillemonchicourt** [comment]
Oui et même plus largement ce terme a peu de sens dans ce module et porte à confusion. 

Les ZP sont dans le protocole Flore prioritaire mais pas dans le protocole SFT.

**Comment by jpm-cbna** [comment]
Seul les scripts d'import ont encore des références aux ZP. Mais cela peut paraitre logique puisque les sites sont issus des ZP du module Flore Prioritaire.
