### ISSUE TITLE
Settings.ini / Infos BDD + autres

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_suivi_flore_territoire#57]
Depuis la version 2.0.0.rc4 de GeoNature, il n'est plus nécessaire de renseigner les infos de la BDD GeoNature pour installer un sous-module. Voir https://github.com/PnX-SI/GeoNature/blob/master/docs/CHANGELOG.rst#200-rc4-2019-01-15
On utilise l'instance ``DB`` pour cela. 

Plus globalement, le fichier ``settings.ini``devrait être minimaliste avec les infos essentielles à l'installation uniquement. Là il reprend des éléments de configuration (``dataset_id``, ``observers_list_id``...) et beaucoup de choses liées à l'import. 

Pas mal de paramètres sont indiqués en "Do not change". Dans ce cas là, pourquoi sont-ils proposés ?

**Comment by jpm-cbna** [comment]
Ok. Je vais déplacer les paramètres nécessaires seulement aux imports dans un fichier de configuration spécifique qui héritera du fichier settings.ini.

Pour les paramètres "do not change", je vais m'assurer que tous les fichiers du module utilisent bien le paramètre et non la valeur correspondante en dur. Je supprimerai ensuite cette mention dans le fichier settings.sample.ini.

**Comment by jpm-cbna** [comment]
La gestion des fichiers de config a été simplifiée en utilisant un fichier de config par défaut que le fichier 'settings.ini' vient surchargé.

Le processus d'installation du module créé automatiquement les fichiers _settings.ini_ et _imports_settings.ini_ à partir des fichiers exemples. Il ajoute aussi le lien vers le fichier de config de GeoNature dans les paramètres du fichier 'settings.ini' afin de supprimer l'obligation de stocker à nouveau les paramètres de connexion à la base de données.

Un script lancer à l'installation se charge d'installer les paquets systèmes nécessaires au module.
