### ISSUE TITLE
Intersection ZP et communes

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_suivi_flore_territoire#9]
A vérifier. 
Calculé automatiquement par trigger remplissant cor_site_area ?

**Comment by gildeluermoz** [comment]
A priori ce trigger n'est pas spécifique à SFT mais générique à gn_monitoring pour intersecter tous les sites et les areas.
Vous l'avez prévu comme ça ?

Je vois les choses ainsi :
Il est sur la table t_sites on insert or update or delete avec action sur le contenu de cor_site_area.
Sur la table t_area il faut aussi prévoir un trigger qui recalcule les intersections avec les sites en cas d'ajout ou de modification d'une area.
Que faire si une area est supprimée ? Faut-il bloquer avec un no action ? Peut on considérer que le lien d'intersection avec un site peut automatiquement disparaitre ?
Je dirais que oui et que donc on peut mettre un delete cascade sur la FK de cor_site_area.

Un trigger delete qui agit sur cor_site_area serait equivalent.

**Comment by camillemonchicourt** [comment]
Oui c'est bien ça qu'on avait en tête mais on voulait verifier le fonctionnement, verifier qu'on filtre bien les bons id_type_area et que ces id sont paramétrables etc...

En effet si on supprime une area il faut supprimer la correspondance avec le site dans la table de correspondance.

**Comment by camillemonchicourt** [comment]
Actuellement il y a le trigger sur l'insertion et la modification de la géométrie d'un site pour remplir la table ``cor_site_area`` : https://github.com/PnX-SI/GeoNature/blob/develop/data/core/monitoring.sql#L167-L185

Côté backend, il y a une route qui renvoie la géométrie des zonages intersectant un site : https://github.com/PnX-SI/GeoNature/blob/develop/backend/geonature/core/gn_monitoring/routes.py#L83

Dans notre cas, ce n'est pas la géométrie des zonages dont on a besoin mais uniquement leur nom. 
Pour le moment, une route a été ajoutée dans le module pour cela, mais à regrouper à terme.

**Comment by camillemonchicourt** [comment]
Le trigger qui remplit ``cor_site_area`` au niveau de ``gn_monitoring`` fonctionne bien. 
Il permet aussi de faire association entre mailles et ZP si les mailles du territoire ont été intégrées avant les ZP.

Reste à migrer la route qui retourne le nom des communes d'un site de suivi dans le cœur du module gn_monitoring.

**Comment by camillemonchicourt** [comment]
Intersection sites et zonages OK.
Reste la route à migrer : https://github.com/PnX-SI/gn_module_suivi_flore_territoire/issues/29
